# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4145a80fa2cbd9cdfefb60d1fe958c65c2fdab9bde4a97df699d4716877a47f1264b94208532652f87abbacd67fecdb5a1c1ed5ed9393d2b01fb5a55096fd931

test:
  secret_key_base: 3217e2dcf6c560c1e67ddf0024aa4cd44226b2c98e042466c4676b0f796a8387f8fac2f7472e054f7837e974f6914344e60b727d13d043669edeaf0fa17a507f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
